# Generated by Django 3.1.2 on 2020-12-10 18:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20201208_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
